sitename: The Cornbread Companion
baseurl: ""
permalink: /:year/:month/:title/
markdown: rdiscount
prose:
  rooturl: '_posts'
  siteurl: 'http://cornbreadcompanion.com'
  relativeLinks: 'http://cornbreadcompanion.com/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "banner"
        field:
          element: "text"
          label: "Banner Image"
          value: ""
      - name: "preview"
        field:
          element: "text"
          label: "Preview Image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Art"
              value: "art"
            - name: "Books"
              value: "books"
            - name: "Death"
              value: "death"
            - name: "Family"
              value: "family"
            - name: "Food"
              value: "food"
            - name: "Jesus"
              value: "jesus"
            - name: "Life"
              value: "life"
            - name: "Music"
              value: "music"
            - name: "Travel"
              value: "travel"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "banner"
        field:
          element: "text"
          label: "Banner Image"
          value: ""
